### ISSUE TITLE
Editing the config file appears to add a space manually to the steamcmd queries

### ISSUE THREAD

**Issue by RisingManes** [thakyZ/MultiBound2#1]
I'm not sure how else to word this, so I apologize if it's unclear.

I figured out how to enter login credentials by [editing the config file itself](https://imgur.com/iTXd4ni). However, if the steamcmd.txt file generated by Multibound2 is any indication, it appears to [add an additional space](https://imgur.com/Cn7eT6D) to the actual command sent to steamcmd.

There is another issue pertaining to the order these commands are sent out, which I submit as a separate issue.

**Comment by thakyZ** [comment]
This is because you have the password set as anonymous and the username blank, so it place a space around where the username should be, with a space already around it, it will follow with the password.
```login test 1234``` but since you have no username it ends up being ```login  1234``` with two spaces of course.

**Comment by thakyZ** [comment]
It should work if you were to use a username, because the username is required while the password isn't exactly.
