### ISSUE TITLE
Steamcmd now requires force_install_dir before login

### ISSUE THREAD

**Issue by RisingManes** [thakyZ/MultiBound2#2]
Related to #1.

steamcmd [no longer accepts `force_install_dir`](https://imgur.com/IYp4C7j) when you are already logged in, and sends an error message asking for such. I do not know what prompted this change, but it breaks Multibound2's functionality.

**Comment by thakyZ** [comment]
Do you know how you got the program to use Steam CMD in the first place? Because I just realized I didn't pack some files correctly, and it was crashing when I tried to update workshop files and trying to download them as well.
Also I am currently working on this :3

**Comment by RisingManes** [comment]
The original Multibound2 would download steamcmd onto %appdata%/local/multibound/steamcmd as part of its installation process. Before you released your branch, I was using ZetaPRIME's. But the original author appears to have abandoned the project altogether, hence my using this branch.

**Comment by thakyZ** [comment]
Okay cool! I did a bit more testing than I could do last night. But I did make sure it correctly downloads SteamCMD and I made sure it inserts the `force_install_dir` before the login. I hope you have a wonderful day. And I am very sorry for the confusion last night, it was late, and I was really sleepy.
